# Added 3.21
type AbyssBossLifeScalingPerLevel {
  _: i32 @unique
  _: i32 @unique
}

# Added 3.21
type ActiveSettings {
  _: string @unique
  _: i32 @unique
  _: i32 @unique
  _: rid @unique
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
}

# Added 3.19
type AlternateTreeArt {
  _: rid @unique
  _: string @unique
  _: string @unique
  _: string @unique
}

# Added 3.21
type AnimateWeaponUniques {
  _: string @unique
  _: rid
  _: rid
  _: i32
}

# Added 3.19
type AtlasMemoryLine {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
}

# Added 3.17
type BattlePasses {
  _: string @unique
  _: i32 @unique
  _: string @unique
  _: string @unique
  _: i32
  _: bool
  _: string @unique
}

# Added 3.17
type BattlePassRewards {
  _: rid
  _: i32
  _: bool
  _: i32
  _: i32 # All rows empty
  _: string
  _: [string]
  _: i32 # All rows empty
  _: string
  _: string
  _: i32
  _: i32
  _: bool
  _: string
  _: rid
  _: bool
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
}

# Added 3.21
type BattlePassTracks {
  _: string @unique
  _: string @unique
}

# Added 3.20
type BreachArtVariations {
  _: string @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: [_]
  _: rid @unique
}

# Added 3.21
type Breachstones {
  _: rid @unique
  _: i32
  _: i32 @unique
  _: rid
  _: rid
}

# Added 3.22
type conditionalachievements {
  _: rid @unique
  _: i32
  _: i32
}

# Added 3.18
type CorpseSinkVariations {
  _: string @unique
  _: string
  _: string
  _: [string]
  _: i32 @unique
  _: bool
  _: i32
  _: i32
  _: bool
}

# Added 3.21
type CosmeticsEquipPanelMode {
  _: string @unique
  _: [_]
}

# Added 3.21
type CraftingBenchSpecificOptionId {
  _: string @unique
  _: string @unique
  _: i32 # All rows empty
  _: i32 # All rows empty
}

# Added 3.21
type CrucibleDifficulty {
  _: string @unique
  _: string @unique
  _: i32 @unique
  _: i32
  _: i32
  _: i32
}

# Added 3.21
type CrucibleEndgameMonsterPacks {
  _: string @unique
  _: [_]
  _: i32
  _: i32
  _: bool
}

# Added 3.21
type CrucibleLifeScalingPerLevel {
  _: i32 @unique
  _: i32
}

# Added 3.21
type CruciblePlayerClassOffsets {
  _: rid @unique
  _: i32
  _: i32
}

# Added 3.21
type CrucibleTags {
  _: string @unique
  _: bool
}

# Added 3.21
type CurrencyUseEffects {
  _: rid @unique
  _: i32 # All rows empty
  _: string
  _: string
  _: bool
  _: string
  _: bool
  _: rid
  _: f32
}

# Added 3.17
type DamageEffectVariations {
  _: string @unique
  _: [_]
  _: [string]
  _: bool
  _: i32
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: rid
}

# Added 3.20
type DamageWhenHitEffects {
  _: rid @unique
  _: rid @unique
  _: bool
}

# Added 3.20
type DelveRobotVariations {
  _: string @unique
  _: string @unique
  _: [string]
  _: rid @unique
  _: rid @unique
}

# Added 3.22
type divinationwindowvisuals {
  _: string @unique
  _: string @unique
  _: string @unique
}

# Added 3.22
type entityinfobarstyle {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string
  _: string
  _: string @unique
  _: string @unique
  _: string @unique
  _: i32
  _: i32
  _: string
  _: string
  _: string
  _: string
  _: string
}

# Added 3.17
type FlaskStashBaseTypeOrdering {
  _: rid @unique
  _: i32 @unique
}

# Added 3.20
type GameObjectTasksFromStats {
  _: rid @unique
  _: rid
  _: bool
  _: i32
  _: bool
  _: bool
}

# Added 3.17
type GamepadButtonCombination {
  _: string @unique
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
}

# Added 3.17
type GamepadThumbstick {
  _: string @unique
  _: string @unique
}

# Added 3.20
type GoldActScaling {
  _: string @unique
  _: i32
  _: i32 @unique
  _: i32 @unique
}

# Added 3.20
type GoldConstants {
  _: string
  _: i32
}

# Added 3.20
type HardModeExtraContentChances {
  _: string @unique
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
}

# Added 3.22
type hardmodeextracontentchancespermaptier {
  _: rid @unique
  _: i32 # All rows empty
}

# Added 3.19
type HarvestCraftCostScalingByBasetype {
  _: rid
  _: rid @unique
  _: i32
}

# Added 3.20
type HideoutCraftingBenchDoodads {
  _: rid @unique
  _: rid @unique
}

# Added 3.20
type HideoutCraftingBenchInterfaceVisuals {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
}

# Added 3.20
type HideoutStashDoodads {
  _: rid @unique
  _: bool
  _: bool
  _: bool
}

# Added 3.19
type HideoutWaypointDoodads {
  _: rid @unique
  _: [_]
}

# Added 3.21
type HudEnergyShieldVisuals {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: bool
}

# Added 3.21
type HudLifeVisuals {
  _: string @unique
  _: string @unique
  _: string @unique
  _: [_]
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string
  _: string
  _: string @unique
  _: bool @unique
  _: bool
  _: bool
  _: bool
}

# Added 3.21
type HudVisualsFromStat {
  _: rid @unique
  _: rid
  _: rid
  _: rid
}

# Added 3.22
type itemclasspickupeffect {
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
}

# Added 3.22
type itemclassvisualreplacement {
  _: rid @unique
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
}

# Added 3.22
type itempickupeffect {
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: i32 # All rows empty
}

# Added 3.20
type ItemVisualReplacement {
  _: rid
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
}

# Added 3.17
type LegacyAtlasInfluenceOutcomes {
  _: string @unique
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: [_]
}

# Added 3.22
type mapstashsubstashgroup {
  _: string @unique
  _: string @unique
  _: string
  _: rid
  _: string @unique
}

# Added 3.19
type MemoryLineType {
  _: string @unique
  _: rid
  _: i32 @unique
  _: [_]
  _: [_]
  _: i32
  _: i32 @unique
  _: rid @unique
  _: i32 # All rows empty
  _: string @unique
  _: rid
}

# Added 3.19
type MicrotransactionAppliedInventoryItemArtVariations {
  _: rid @unique
  _: [string]
  _: [_]
  _: [_]
  _: [_] # All rows empty
}

# Added 3.18
type MicrotransactionChargeVariations {
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
}

# Added 3.19
type MicrotransactionConditionalApparitionEvents {
  _: rid
  _: i32 # All rows empty
  _: i32
  _: rid
  _: bool
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
}

# Added 3.19
type MicrotransactionConditionalApparitions {
  _: string @unique
  _: [_]
  _: [_]
  _: rid @unique
  _: rid
  _: i32
  _: bool
  _: i32
  _: bool
}

# Added 3.21
type MicrotransactionEquippedIconVariations {
  _: rid
  _: [string]
  _: [_]
}

# Added 3.17
type MicrotransactionJewelVariations {
  _: rid @unique
  _: i32 @unique
  _: string @unique
  _: string
  _: i32
  _: [_]
  _: string
  _: string
  _: i32 # All rows empty
  _: i32
  _: string
  _: i32
  _: string
  _: i32
  _: bool
  _: rid
  _: bool
}

# Added 3.21
type MicrotransactionObjectEffects {
  _: string @unique
  _: [_]
  _: string
  _: [_]
  _: [_]
  _: rid
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
}

# Added 3.21
type MicrotransactionOnKillBeams {
  _: string
  _: rid
  _: string
  _: string
  _: string
  _: bool
  _: rid
}

# Added 3.21
type MicrotransactionOnKillConditions {
  _: string @unique
  _: [_]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: bool
  _: i32 # All rows empty
  _: [_]
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: bool
  _: i32 @unique
  _: i32 # All rows empty
}

# Added 3.21
type MicrotransactionOnKillEffects {
  _: string @unique
  _: rid
  _: rid @unique
  _: rid
  _: i32 @unique
  _: rid
  _: i32
}

# Added 3.22
type miniontype {
  _: string @unique
  _: rid
  _: rid
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
}

# Added 3.19
type PassiveJewelArt {
  _: rid @unique
  _: string
  _: string
  _: rid
}

# Added 3.18
type PortalAudio {
  _: rid
  _: rid
  _: rid @unique
  _: i32
}

# Added 3.18
type PortalAudioEvents {
  _: string @unique
  _: i32
}

# Added 3.21
type PreloadFromStats {
  _: rid @unique
  _: [_]
  _: [_] # All rows empty
  _: [_]
  _: [_]
  _: i32
}

# Added 3.20
type RelicInventoryLayout {
  _: i32
  _: i32
  _: i32
  _: string
}

# Added 3.20
type RelicItemEffectVariations {
  _: string @unique
  _: string @unique
  _: string @unique
}

# Added 3.20
type ShrineVisualArtVariations {
  _: rid @unique
  _: bool
  _: rid @unique
  _: bool
  _: bool
  _: bool
}

# Added 3.19
type SkillGemLevelUpEffects {
  _: string @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
  _: rid @unique
}

# Added 3.19
type StampChoice {
  _: string @unique
  _: rid
  _: i32
  _: string
  _: string
  _: rid
  _: [_]
  _: i32
}

# Added 3.19
type StampFamily {
  _: string @unique
  _: i32
}

# Added 3.20
type StatsFromSkillStats {
  _: rid
  _: rid
}

# Added 3.20
type StatVisuals {
  _: rid @unique
  _: [string]
  _: bool
}

# Added 3.19
type TieredMicrotransactions {
  _: rid @unique
  _: [_]
  _: rid
  _: [_]
  _: rid
  _: i32
  _: [_]
  _: [_]
  _: [_]
  _: bool
  _: bool
  _: rid
}

# Added 3.22
type tieredmicrotransactionsvisuals {
  _: rid
  _: i32 @unique
  _: string @unique
  _: string @unique
  _: i32 @unique
}

# Added 3.22
type tormentedspiritlifescalingperlevel {
  _: i32 @unique
  _: i32
}

# Added 3.19
type TradeMarketImplicitModDisplay {
  _: rid @unique
  _: string
}

# Added 3.21
type TryTheNewLeagueVersions {
  _: string @unique
  _: string
}

enum ancestraltrialmonsterranks @indexing(first: 0) { _ }

enum ancestraltrialopiniontypes @indexing(first: 0) { _ }

enum ancestraltrialshopslots @indexing(first: 0) { _ }

enum ancestraltrialunittypes @indexing(first: 0) { _ }

enum AtlasEntities @indexing(first: 0) { _ }

enum BattlePassRewardTypes @indexing(first: 0) { _ }

enum CustomLeagueTemplate @indexing(first: 0) { _ }

enum DamageHitTypes @indexing(first: 0) { _ }

enum DropReplacementCustomReplacements @indexing(first: 0) { _ }

enum DropReplacementCustomTargets @indexing(first: 0) { _ }

enum duplicategrantedeffect @indexing(first: 0) { _ }

enum mapdevicecustomeffects @indexing(first: 0) { _ }

enum MicrotransactionConditionalApparitionEventType @indexing(first: 0) { _ }

enum MicrotransactionConditionalApparitionOrientation @indexing(first: 0) { _ }

enum MicrotransactionConditionalApparitionPosition @indexing(first: 0) { _ }

enum MonsterPushTypes @indexing(first: 0) { _ }

enum NPCShopSellPriceType @indexing(first: 0) { _ }

enum OnHitEffectTarget @indexing(first: 0) { _ }

enum PantheonMapBossSelection @indexing(first: 0) { _ }

enum passiveskilltattootargets @indexing(first: 0) { _ }

enum passivetattoovendorgroups @indexing(first: 0) { _ }

enum ProjectileCollisionTypes @indexing(first: 0) { _ }

enum RarityMask @indexing(first: 0) { _ }

enum SanctumEffectTriggers @indexing(first: 0) { _ }

enum SanctumImmediateEffectType @indexing(first: 0) { _ }

enum SanctumPersistentEffectFamily @indexing(first: 0) { _ }

enum SkillWeaponEffects @indexing(first: 0) { _ }

enum UserInterfaceModeCondition @indexing(first: 0) { _ }
