# Added 4.2
type AchievementItemRewards @tags(list: ["mtx:reward"]) {
  AchievementItem: AchievementItems
  Rewards: MtxTypeGameSpecific
  MessagePC: string @localized
  Id: string @unique
  MessageConsole: string @localized
}
