# Added 4.1
type ActiveSettings {
  Id: string @unique
  _: i32
  _: i32
  _: i32
  LeagueInfoPanel: LeagueInfoPanelVersions
  NewLeaguePopup: TryTheNewLeagueVersions
  Logo: GameLogos
  BackendError: BackendErrors
}
