# Added 4.1
type Acts {
  Id: string @unique
  UI_Title: string @localized
  ActNumber: i32
  _: string
  _: string
  _: i32
  IsEndGame: bool
  _: i32
  QuestFlags1: [QuestFlags]
  _: [rid]
  _: [rid]
  WorldAreaMap: WorldAreas
  QuestFlags2: [QuestFlags]
  Description: string @localized
  _: rid
  _: bool
  WorldAreaTown: WorldAreas
}
