# Added 4.1
type AddBuffToTargetVarieties {
  BuffDefinitions: BuffDefinitions
  _: [i32]
  Stats1Keys: [Stats]
  Stat1Values: i32
  _: i32
  _: i32
  Stat2Values: [i32]
  Stats2Keys: [Stats]
  _: [i32]
  _: bool
}
