# Added 4.1
type AlternateQualityTypes @tags(list: ["item:def"]) {
  Id: string @unique
  Description: string @localized
  Item: BaseItemTypes
  ModEffectStat: ModEffectStats
  HASH16: u16
  ItemClass: [ItemClasses]
}
