# Added 4.2
type AlternateCharacterSkin {
  Id: string @unique
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
  _: string
}
