# Added 4.1
type AtlasInfluenceData {
  InfluencePack: AtlasInfluenceOutcomes
  MonsterPacks: [MonsterPacks]
  BuffDefinition: BuffDefinitions
  SpawnChanceStat: [Stats]
  BuffStatValues: [i32]
  SpawnChanceValue: [i32]
  _: i32
  _: i32
  InfluencePackSizeStat: Stats
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
