# Added 4.1
type AtlasInfluenceData {
  InfluencePack: AtlasInfluenceOutcomes
  MonsterPacks: [MonsterPacks]
  BuffDefinition: BuffDefinitions
  _: [Stats]
  BuffStatValues: [i32]
  _: [_]
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: u16 # All rows empty
  _: bool
}
