# Added 4.2
type AzmeriWoodsDustType {
  Id: string @unique
  Name: string @localized
  Icon: string
  WeatherArt: MiscAnimated
  BeamArt: MiscBeams
  Text: string @localized
  _: rid @unique
  _: [_]
  _: rid @unique
  _: rid @unique
  _: rid @unique
}
