# Added 4.1
type BaseItemTypes @tags(list: ["item:def", "item:droptable"]) {
  Id: string @unique
  ItemClass: ItemClasses
  Width: i32
  Height: i32
  Name: string @localized
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  DropLevel: i32
  FlavourText: FlavourText
  Implicit_Mods: [Mods]
  SizeOnGround: i32
  SoundEffect: SoundEffects
  Tags: [Tags]
  ModDomain: ModDomains
  SiteVisibility: i32
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32 @unique
  _: [_] # All rows empty
  _: string @localized
  _: rid
  _: bool
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
  _: bool
  _: bool
  _: [_] # All rows empty
  _: rid
  _: rid
}
