# Added 4.1
type BattlePasses {
  Id: string @unique
  LeagueCategory: i32
  International_BK2File: string @localized
  China_BK2File: string @localized
  MapCompletionCount: i32
  _: bool
  _: string @unique
  _: rid @unique
}
