# Added 4.1
type BattlePasses {
  Id: string @unique
  LeagueCategory: LeagueCategory
  International_BK2File: string @localized
  China_BK2File: string @localized
  MapCompletionCount: i32
  _: bool
  Id2: string @unique
  _: rid @unique
}
