# Added 4.1
type BestiaryFamilies {
  Id: string @unique
  Name: string @localized
  Icon: string
  IconSmall: string
  Illustration: string
  PageArt: string
  FlavourText: string @localized
  _: bool
  TagsKey: Tags
  _: i32
  ModsKeys: [Mods]
  CurrencyItemsKey: CurrencyItems
}
