# Added 4.1
type BloodTypes {
  Id: string @unique
  GroundEffect: [GroundEffects]
  Visual: BuffVisuals
  VisualMoving: BuffVisuals
  _: f32
  _: f32
  _: f32
  DeathEffect: [MiscEffectPacks]
  _: [string]
  CorpseExplodeEffect: MiscEffectPacks
}
