# Added 4.1
type BreachArtVariations {
  Id: string @unique
  Portal: MiscAnimated
  Chest: MiscAnimated
  LargeChest: MiscAnimated
  Effect: MiscAnimated
  BuffVisualSmall: BuffVisuals
  BuffVisualBig: BuffVisuals
  LargeChestMarker: MiscAnimated
  SoulerCoaster: [MiscAnimated]
  CloseEffect: MiscAnimated
}
