# Added 4.5
type BreachStashTabLayout {
  Id: string @unique
  BaseItemType: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  SlotStyle: StashTabInventorySlotStyle
}
