# Added 4.5
type BrequelFruitRewardTypes {
  Id: string @unique
  Name: string @localized
  Description: string @localized
  PCPrompt: string @localized
  ConsolePrompt: string @localized
  _: [_] # All rows empty
  _: i32
  _: i32
  _: rid
}
