# Added 4.1
type CharacterAudioEvents {
  Id: string @unique
  Event: QuestFlags
  _: i32
  _: i32
  "For the Goddess Bound/Scorned/Unleashed unique"
  Goddess_CharacterTextAudioKeys: [CharacterTextAudio]
  "For Jack the Axe unique"
  JackTheAxe_CharacterTextAudioKeys: [CharacterTextAudio]
  _: bool
  _: bool
  Cooldown: [MiscCooldowns]
  _: CharacterAudioEvents
  _: bool
  QuestFlag: [QuestFlags]
  _: rid
  _: CharacterAudioEvents
  _: i32
  _: i32
}
