# Added 4.1
type CharacterStartStates {
  Id: string @unique
  Description: string @localized
  Character: Characters
  Level: i32
  PassiveSkillsKeys: [PassiveSkills]
  CharacterStartStateSet: CharacterStartStateSet
  HubArea: WorldAreas
  CharacterStartQuestStates: [CharacterStartQuestState]
  _: bool
  InfoText: string
  Ascendancy: Ascendancy
  _: [rid]
  _: [rid]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [rid]
  _: [rid]
  _: bool
}
