# Added 4.1
type CharacterPanelStats {
  Id: string @unique
  Text: string @localized
  StatsKeys1: [Stats]
  CharacterPanelDescriptionModesKey: CharacterPanelDescriptionModes
  StatsKeys2: [Stats]
  StatsKeys3: [Stats]
  CharacterPanelTabsKey: CharacterPanelTabs
  _: bool
  _: [i32]
  _: i32
  StatsKeys4: [Stats]
  _: bool
  StatsKeys5: [Stats]
  _: bool
  StatsKeys6: [Stats]
}
