# Added 4.1
type Chests {
  Id: string @unique
  _: bool
  _: i32
  Name: string @localized
  AOFiles: [string] @file(ext: ".ao")
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: [rid]
  BaseItemTypesKey: BaseItemTypes
  _: bool
  ModsKeys: [Mods]
  TagsKeys: [Tags]
  ChestEffectsKey: ChestEffects
  MinLevel: i32
  _: string @localized
  MaxLevel: i32
  _: rid
  UnlockItem: BaseItemTypes
  Encounter_AchievementItemsKeys: [AchievementItems]
  Environment: Environments
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  _: bool
  MinimapIcons: MinimapIcons
  _: [rid]
  _: string
  _: i32
  _: i32
  _: bool
  Colour: Colours
  OutlineColour: Colours
  _: bool
  _: bool
  LeagueChallenges: [AchievementItems]
  IsHardmode: bool
  StatsHardmode: [Stats]
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: rid
  _: bool
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
}
