# Added 4.1
type ClientStrings2 {
  Id: string @unique
  Text: string @localized
  XBoxText: string @localized
  XBoxText2: string @localized
  HASH32: u32
  PlaystationText: string @localized
  _: string
}
