# Added 4.1
type CoreLeagues {
  Id: string @unique
  _: bool
  _: bool
  _: Stats
  _: [Stats]
  _: Stats
  _: Stats
  _: Stats
  _: [Stats]
  _: Stats
  _: rid
  _: i32
  _: bool
  _: Stats
  _: bool
  _: bool
  _: [Stats]
  _: bool
  _: i32
  MapObjective: EndgameMapObjectives
}
