# Added 4.3
type CraftingSpreeType @tags(list: ["crafting"]) {
  Id: string @unique
  CurrencyItem: [CurrencyItems]
  CurrencyCount: [i32]
  ItemClass: [ItemClasses]
  _: bool
  Text: string @localized
  _: i32
}
