# Added 4.1
type CraftingBenchOptions @tags(list: ["crafting"]) {
  Id: string @unique
  _: string
  _: [_] # All rows empty
  _: string
  SortCategory: CraftingBenchSortCategories
  _: i32
  _: [rid]
  _: [rid]
  CraftingCategory: [CraftingItemClassCategories]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: bool
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: rid
  _: rid
  _: bool
}
