# Added 4.1
type CurrencyExchange {
  Item: BaseItemTypes
  Category: CurrencyExchangeCategories
  SubCategory: CurrencyExchangeCategories
  _: bool
  EnabledInChallengeLeague: bool
  GoldPurchaseFee: i32
  _: bool
}
