# Added 4.1
type CurrencyStashTabLayout {
  Id: string @unique
  StoredItem: BaseItemTypes
  XOffset: i32
  YOffset: i32
  FirstSlotIndex: i32
  Width: i32
  Height: i32
  ShowIfEmpty: bool
  SlotGroup: i32
  _: string
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32 # All rows empty
}
