# Added 4.1
type DamageParticleEffects {
  DamageParticleEffectTypes: DamageParticleEffectTypes
  Variation: i32
  _: i32
  DamageEffect: DamageEffectVariations
  EffectAddon: DamageEffectVariations
  _: bool
}
