# Added 4.1
type damagecalculationtypes {
  _: string @unique
  _: [_]
  _: [_]
  _: [_]
  _: [_]
  _: [_]
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: string @unique
  _: rid
  _: i32
  _: bool
  _: rid
  _: rid
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
}
