# Added 4.1
type DamageEffectVariations {
  Id: string @unique
  MiscAnimated: [MiscAnimated]
  Particles: [string] @file(ext: ".pet")
  _: i32
  _: i32
  _: [string]
  _: [string]
  EffectPack: MiscEffectPacks
  _: bool
  _: bool
}
