# Added 4.1
type DefaultMonsterStats {
  DisplayLevel: string
  Damage: f32
  Evasion: i32
  Accuracy: i32
  MonsterLife: i32
  Experience: i32
  AllyLife: i32
  Armour: i32
  Difficulty: i32
  MinionDamage: f32
  EvasiveEvasion: i32
  AilmentThreshold: i32
  PoiseThreshold: i32
  AltLife2: i32
  LeechResistance: i32
  MoreElementalDamage: i32
  MoreChaosDamage: i32
  RareUniqueLeechResistance: i32
  UniqueMonsterDamageTakenFromMinions: i32
  MoreDamageAgainstNonUnique: i32
  _: i32
}
