# Added 4.1
type DelveFeatures {
  Id: string @unique
  Name: string @localized
  SpawnWeight: [i32]
  WorldAreasKey: WorldAreas
  Image: string
  AchievementItemsKeys: [AchievementItems]
  _: [i32]
  MinDepth: [i32]
  Description: string @localized
  _: i32
  _: [i32]
  _: [i32]
  _: [i32]
  _: [i32]
}
