# Added 4.2
type displaycasetypes {
  _: string @unique
  _: bool @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: u16 # All rows empty
  _: bool
}
