# Added 4.1
type EffectDrivenSkill {
  _: i32
  Animation: [MiscAnimated]
  _: [_] # All rows empty
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
}
