# Added 4.1
type EndgameMapPins {
  Id: string @unique
  UnavailablePin: MiscAnimated
  AvailablePin: MiscAnimated
  ActivePin: MiscAnimated
  FailedPin: MiscAnimated
  CompletePin: MiscAnimated
  HighlightEPK: string @file(ext: ".epk")
  RevealAnimation: MiscAnimated
  RitualHighlightEPK: string @file(ext: ".epk")
  RitualSelectedEPK: string @file(ext: ".epk")
  DeliriumHighlightEPK: string @file(ext: ".epk")
  AudioAnimation: MiscAnimated
}
