# Added 4.1
type EndgameMaps {
  _: i32
  _: rid
  _: rid @unique
  _: [_]
  _: [_]
  _: string @localized
  _: i32
  _: [_]
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32
  _: rid
  _: i32 # All rows empty
  _: rid
  _: [_]
}
