# Added 4.4
type EndgameMapTablets {
  BaseItemType: BaseItemTypes
  MapStats: [Stats]
  MapStatValues: [i32]
  TowerStat: Stats
  MapObjective: EndgameMapObjectives
  MapContent: EndgameMapContent
  League: CoreLeagues
}
