# Added 4.1
type EndgameMapContent {
  Id: string @unique
  Stats: [Stats]
  StatValues: [i32]
  Description: string @localized
  Name: string @localized
  _: i32
  MapObjective: EndgameMapObjectives
  VisualIdentity: EndgameMapContentVisualIdentity
  _: bool
}
