# Added 4.5
type EndgameRegionActionCurrencyItems {
  Region: EndgameRegionActionButtons
  _: i32
  BaseItemTypes: BaseItemTypes
  KeywordPopup: KeywordPopups
  ErrorDescription: ClientStrings2
  _: bool
  _: i32
  _: i32
  _: rid
}
