# Added 4.5
type EndgameRegionActionButtonsRequiredQuestFlags {
  Button: EndgameRegionActionButtons
  _: i32
  _: rid
  _: i32
  QuestItem: BaseItemTypes
  ErrorDescription: ClientStrings2
  _: bool
  KeywordPopup: KeywordPopups
}
