# Added 4.5
type EndgameMapAtlasTowers {
  RevealType: EndgameMapRevealTypes
  _: i32
  AtlasNodes: [EndgameMapAtlas]
  SessionQuestFlag: SessionQuestFlags
  TowerAtlas: [EndgameMapAtlas]
  FortressAtlas: [EndgameMapAtlas]
}
