# Added 4.1
type EndgameMapBiomes {
  Id: string @unique
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  _: i32
  Name: string @localized
  _: rid
  WorldArea: WorldAreas
  _: [i32]
  AreaTag: Tags
  MonsterTag: Tags
  Stat: Stats
  GroundType: EndgameMapBiomeGroundTypes
}
