# Added 4.5
type EndgameMapAtlas {
  _: PassiveSkills
  _: [EndgameMaps]
  _: i32
  _: [rid]
  _: i32
  _: rid
  Stats: [Stats]
  StatValues: [i32]
  _: rid
  _: i32
  _: rid
  _: bool
  _: bool
  _: bool
  _: rid
  _: i32
  _: i32
  _: rid
  _: i32
  _: EndgameMapAtlas
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
}
