# Added 4.5
type EndgameMapAtlas {
  Passives: PassiveSkills
  Map: [EndgameMaps]
  _: i32
  Biome: [EndgameMapBiomes]
  _: i32
  _: rid
  Stats: [Stats]
  StatValues: [i32]
  MapPin: EndgameMapPins
  _: i32
  BlockedMessage: ClientStrings2
  _: bool
  _: bool
  _: bool
  SubTree: AtlasPassiveSkillSubTrees
  _: i32
  _: i32
  MapObjective: EndgameMapObjectives
  _: i32
  _: EndgameMapAtlas
  BiomeGroundType: EndgameMapBiomeGroundTypes
  MapDecoration1: EndgameMapDecorations
  MapDecoration2: EndgameMapDecorations
  Quest: Quest
  _: i32
  _: i32
  _: bool
  _: bool
  ClientString: ClientStrings2
}
