# Added 4.1
type EndgameMaps {
  WorldArea: WorldAreas @unique
  _: [rid]
  FlavourText: string @localized
  _: i32
  _: [i32]
  MapPin: EndgameMapPins
  Decorations: EndgameMapDecorations
  MapContentSet: EndgameMapContentSet
  CorruptedPin: EndgameMapPins
  _: i32
  _: i32
  MapPinCompleted: EndgameMapPins
  ObjectiveDescription: ClientStrings2
  SpecialMapText: string @localized
  SpecialMapFlavourText: string @localized
  SpecialMapHelpText: string @localized
  _: i32
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  _: bool
  _: [rid]
  _: bool
  _: string @localized
  _: f32
}
