# Added 4.3
type EndgameSplinterRecipes {
  BaseItemType: BaseItemTypes
  Difficulty: i32
  Cost: i32
  DestinationArea: WorldAreas
  _: i32
  _: rid
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
}
