type EndgameMapBiomeGroundTypes {
  Id: string @unique
  _: string @file(ext: ".gt")
  _: string @file(ext: ".gt")
  _: string @file(ext: ".gt")
  _: string @file(ext: ".gt")
  _: string @file(ext: ".gt")
  _: string @file(ext: ".gt")
}
