# Added 4.1
type Environments {
  Id: string @unique
  Base_ENVFile: string @file(ext: ".env")
  Corrupted_ENVFiles: [string] @file(ext: ".env")
  QuestFlag1: [QuestFlags]
  QuestFlag2: [QuestFlags]
  _: [i32]
  EnvironmentTransitionsKey: EnvironmentTransitions
  PreloadGroup: PreloadGroups
  _: bool
  _: f32
}
