# Added 4.1
type Essences {
  BaseItemType: BaseItemTypes @unique
  HASH32: u32
  _: i32
  _: i32
  _: i32
  _: i32 # All rows empty
  _: [_]
  _: [_]
  _: rid @unique
  _: bool
  _: i32
  _: i32
  _: i32
  _: rid
}
