# Added 4.1
type ExecuteGEAL {
  Id: string @unique
  MiscAnimated: [MiscAnimated]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: [_] # All rows empty
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  Script: string
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  MetadataIDs: [string] @files(ext: [".ot", ".otc"])
  ScriptCommand: string
  _: string
  _: string
  _: string
  _: string
  _: i32
  _: bool
  _: bool
  _: [_] # All rows empty
  _: i32
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
}
