# Added 4.1
type ExpeditionBalancePerLevel {
  Level: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: f32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: f32
  _: i32
  _: i32
}
