# Added 4.5
type Expedition2RunesWeights {
  Id: string @unique
  RecipeRuneCount: i32
  HighlightedRuneSlot: i32
  HighlightedRune: Expedition2Runes
  MinAreaLevel: i32
  MaxAreaLevel: i32
  _: i32
  TableComments: string
  _: bool
  _: i32
}
