# Added 4.3
type fragmentsubstashtablayout {
  _: string @unique
  _: rid
  _: rid
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: rid
  _: bool
  _: i32
  _: rid
  _: rid
  _: i32 # All rows empty
}
