# Added 4.3
type FragmentSubStashTabLayout {
  Id: string @unique
  SubStash: FragmentSubStashes
  StoredItem: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  SubStashPage: FragmentStashSubPages
  _: bool
  _: i32
  ItemClass: ItemClasses
  StashPages: FragmentStashPages
  _: i32
}
