# Added 4.3
type FragmentSubStashTabLayout {
  Id: string @unique
  SubStash: FragmentSubStashes
  StoredItem: BaseItemTypes
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: bool
  _: i32
  _: rid
  _: rid
  _: i32
}
