# Added 4.1
type GenericSkillIndicator {
  Stat: Stats @unique
  Indicator: GameObjectTasks
  Condition: [IndicatorConditions]
  _: [string]
  _: [string]
  _: [string]
  _: [rid]
  _: i32
  MiscAnimated: MiscAnimated
}
