# Added 4.1
type GeometryChannel {
  Id: string @unique
  AnimationStart: Animation
  AnimationEnd: Animation
  MiscAnimated: MiscAnimated
  _: string
  _: string
  _: string
  _: bool
  _: bool
  MiscAnimated2: MiscAnimated
  _: rid
  EPKFile: string @file(ext: ".epk")
  _: i32
  _: i32
}
