# Added 4.1
type GeometryTrigger {
  _: i32
  GrantedEffect: GrantedEffects
  Animation: MiscAnimated
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  GroundMarker: [MiscAnimated]
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  MiscAnimated: MiscAnimated
  _: bool
  _: bool
  _: i32
  _: i32
  Stats: [Stats]
  StatValues: [i32]
  _: i32
  _: f32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
}
