# Added 4.1
type graphicalitemreceptacle {
  _: string @unique
  _: string @unique
  _: rid
  _: bool
  _: bool
  _: string
  _: [_] # All rows empty
  _: rid
  _: string @unique
  _: rid @unique
  _: bool
  _: string @unique
  _: string @unique
  _: bool
  _: rid @unique
  _: string @unique
  _: rid @unique
  _: string @unique
}
