# Added 4.1
type GraphicalItemReceptacle {
  Id: string @unique
  _: string
  _: ClientStrings
  _: bool
  _: bool
  SoundEffect: SoundEffects
  _: string
  ErrorMessage: ClientStrings
  Script: string
  _: ClientStrings
  _: bool
  _: string
  _: string
  _: bool
  Name: ClientStrings2
  _: string
  _: ClientStrings
  _: string
}
