# Added 4.5
type GraphicalItemExchangeSlot {
  Item: GraphicalItemExchange
  _: i32
  Inventory: Inventories
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  ItemCondition: [ItemConditions]
  GlowArt: string
  _: i32
  _: string
  _: bool
}
