# Added 4.1
type HardModeExtraContentChances {
  Id: string @unique
  SingleSpawnChance: i32
  DoubleSpawnChance: i32
  TripleSpawnChance: i32
  NoSpawnChance: i32
  Leagues: [CoreLeagues]
  _: [rid]
  CoreLeague: [CoreLeagues]
}
