# Added 4.1
type HarvestCraftOptions @tags(list: ["crafting"]) {
  Id: string @unique
  Text: string @localized
  Tier: HarvestCraftTiers
  Command: string
  Parameters: string
  MirageAchievements: [AchievementItems]
  HASH16: u16
  Description: string @localized
  IsEnchant: bool
  LifeforceType: i32
  LifeforceCost: i32
  SacredCost: i32
  _: bool
  NecropolisAchievements: [AchievementItems]
  _: i32
}
