# Added 4.3
type hideoutsalvagebenchinterfacevisuals {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
}
