# Added 4.1
type Hideouts {
  HideoutArea: WorldAreas
  HASH16: i16
  HideoutFile: string @file(ext: ".hideout")
  ClaimSideArea: WorldAreas
  HideoutImage: string
  IsEnabled: bool
  _: bool
  _: [_]
  _: bool
  _: rid
  _: string
}
