# Added 4.1
type HideoutNPCs {
  Hideout_NPC: NPCs
  HideoutDoodad: HideoutDoodads @unique
  _: rid
  QuestFlag: QuestFlags
  _: i32
  Quest: Quest
  _: i32
  Ruleset: Rulesets
  _: bool
  HideoutDoodads: [HideoutDoodads]
}
