# Added 4.1
type Hideouts {
  HideoutArea: WorldAreas
  HASH16: i16
  HideoutFile: string @file(ext: ".hideout")
  _: rid
  _: string
  _: bool
  _: bool
  _: string @unique
  _: [_]
  _: bool
  _: rid
  _: string
}
