# Added 4.1
type itemvisualheldbodymodeloverridebyitemaffiliatedattributes {
  _: rid @unique
  _: string @unique
  _: string @unique
  _: string
  _: string @unique
  _: string @unique
  _: string
  _: string
}
