# Added 4.1
type ItemisedVisualEffect {
  Mtx: MtxTypeGameSpecific
  VisualEffect: ItemVisualEffect
  VisualIdentity: ItemVisualIdentity
  Stats: [Stats]
  ItemClasses: [ItemClasses]
  BaseItemTypes: [BaseItemTypes]
  _: bool
  _: [i32]
  _: [i32]
  _: bool
  Name: [Words]
  _: bool
  _: [_] # All rows empty
  Character: [Characters]
  GrantedEffect: [GrantedEffectsPerLevel]
  OnKillEffect: [MicrotransactionOnKillEffects]
  _: rid
  _: bool
  EffectSlotType: MicrotransactionSkillGemEffectSlotTypes
  VisualEffectType: ItemisedVisualEffectExclusiveTypes
  _: bool
  _: bool
  GameObjectTask: GameObjectTasks
  _: i32
  _: bool
}
