# Added 4.1
type ItemClasses @tags(list: ["crafting"]) {
  Id: string @unique
  Name: string @localized
  TradeMarketCategory: TradeMarketCategory
  _: bool
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: bool
  _: bool
  _: bool
  _: rid
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: bool
  _: [_]
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
}
