# Added 4.5
type KeywordPopupItemReference {
  Id: string @unique
  BaseItemType: BaseItemTypes
  UniqueName: Words
  ItemVisualIdentity: ItemVisualIdentity
  FlavourText: FlavourText
  Rarity: Rarity
  ItemLevel: i32
  _: bool
}
