type LeaderboardMapDevice {
  Doodad: HideoutDoodads
  Leaderboard: string
  Counter: string
  TrackerPin: string
  Icon: string
  IconHover: string
  IconGlow: string
  Tracker: string
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
