type LeaderboardMapDeviceLabel {
  MapDevice: LeaderboardMapDevice
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  Text: ClientStrings2
  ClientString: ClientStrings
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
