# Added 4.5
type LiquidEmotionOutcomes {
  BaseItemType: BaseItemTypes
  RadiusJewel: i32
  RubyPrefix: Mods
  RubySuffix: Mods
  EmeraldPrefix: Mods
  EmeraldSuffix: Mods
  SapphirePrefix: Mods
  SapphireSuffix: Mods
  DiamondPrefix: Mods
  DiamondSuffix: Mods
  HASH32: u32
}
