# Added 4.1
type MapConnections {
  MapPinsKey0: MapPins
  MapPinsKey1: MapPins
  QuestFlagStart: QuestFlags
  RestrictedAreaText: string @localized
  QuestFlagEnd: QuestFlags
  _: rid
  _: QuestFlags
  _: i32
  _: i32
}
