# Added 4.1
type MapDeviceRecipes @tags(list: ["item:recipe"]) {
  Id: string @unique
  RecipeItems: [BaseItemTypes]
  _: [string]
  MicrotransactionPortalVariation: MicrotransactionPortalVariations
  AreaLevel: i32
  QuestFlag: QuestFlags
  _: i32
  _: bool
  _: bool
  _: bool
  OpenAchievemnts: [AchievementItems]
  _: bool
  Mods: [Mods]
  _: bool
  _: bool
}
