# Added 4.1
type MicrotransactionConditionalApparitions {
  Id: string @unique
  Stats: [Stats]
  StatValues: [i32]
  PeriodicVariation: MicrotransactionPeriodicCharacterEffectVariations
  _: rid
  _: i32
  _: bool
  _: i32
  _: bool
}
