# Added 4.1
type MicrotransactionJewelVariations {
  MtxTypeGameSpecific: MtxTypeGameSpecific @unique
  _: i32
  ActiveArt: string
  BackgroundArt: string
  _: i32
  BackgroundPupil: string
  RadiiArt: PassiveJewelRadiiArt
}
