# Added 4.1
type MicrotransactionSlot {
  Id: i32 @unique
  ShopTag: ShopTag
  Name: string @localized
  InventorySlot: Inventories
  FlaskSlot: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32 @localized
  _: i32 # All rows empty
  _: string
  _: i32
}
