# Added 4.1
type MicrotransactionOnKillConditions {
  Id: string @unique
  Rarity: [MicrotransactionRarityDisplay]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: bool
  _: [i32]
  _: i32
  _: bool
  _: [_] # All rows empty
  Stats: [Stats]
}
