# Added 4.1
type MicrotransactionConditionalApparitionEvents {
  EventId: i32
  Apparition: MicrotransactionConditionalApparitions
  _: f32
  _: NPCTextAudio
  _: bool
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
}
