# Added 4.1
type MicrotransactionObjectEffects {
  Id: string @unique
  _: [_]
  Script: string
  _: [_]
  _: [_]
  _: rid
  _: [_]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
}
