# Added 4.1
type MicrotransactionSlot {
  Id: MicrotransactionSlotId @unique
  _: rid
  Name: string @localized
  _: rid
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: string @localized
  _: string
}
