# Added 4.1
type MinimapIcons {
  Id: string @unique
  MinimapIconRadius: i32
  LargemapIconRadius: i32
  _: bool
  _: bool
  MinimapIconPointerMaxDistance: i32
  _: i32
  _: i32 @localized
  _: i32 # All rows empty
  _: i32
}
