# Added 4.1
type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModType: ModType
  Level: i32
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
  Stat4: Stats
  Domain: ModDomains
  Name: string @localized
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Value: i32
  _: i32
  Stat2Value: i32
  _: i32
  Stat3Value: Tags
  _: i32
  Stat4Value: Tags
  _: GrantedEffectsPerLevel
  SpawnWeight_Tags: [ModAuraFlags]
  _: [i32]
  Tags: [Tags]
  GrantedEffectsPerLevel: [AchievementItems]
  AuraFlags: [ModType]
  _: [i32]
  MonsterMetadata: Stats
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [AchievementItems]
  Stat5Value: Tags
  _: i32
  Stat5: AchievementItems
  FullAreaClear_AchievementItems: [AchievementItems]
  AchievementItems: [Stats]
  GenerationWeight_Tags: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [ItemClasses]
  Stat6Value: i32
  _: i32
  Stat6: AchievementItems
  MaxLevel: i32
  _: Stats
  CraftingItemClassRestrictions: [Stats]
  MonsterOnDeath: string
  _: InfluenceTypes
  HeistAchievements: [Tags]
  Stat7Value: i32
  _: i32
  Stat7: Stats
  Stat8: Stats
  Stat8Value: i32
  _: i32
  InfluenceType: i32
  ImplicitTags: [Tags]
  HasHardmodeStatValues: bool
  Stat1MinHardmode: i32
  Stat1MaxHardmode: i32
  Stat2MinHardmode: i32
  Stat2MaxHardmode: i32
  Stat3MinHardmode: i32
  Stat3MaxHardmode: i32
  Stat4MinHardmode: i32
  Stat4MaxHardmode: i32
  Stat5MinHardmode: BuffTemplates
  Stat5MaxHardmode: Mods
  Stat6MinHardmode: i32
  Stat6MaxHardmode: BuffTemplates
  Stat7MinHardmode: i32
  Stat7MaxHardmode: GrantedEffectsPerLevel
  Stat8MinHardmode: i32
  Stat8MaxHardmode: i32
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: u32 @unique
  BuffTemplate2: [BuffTemplates]
  _: i32
  _: [GrantedEffectsPerLevel]
  RadiusJewelType: i32
  IsEssenceOnlyModifier: bool
  SpawnLevel_Override: i32
  SpawnWeight_Values: [i32]
}
