# Added 4.1
type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModType: ModType
  Level: i32
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
  Stat4: Stats
  Domain: ModDomains
  Name: string @localized
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Value: i32
  _: i32
  Stat2Value: i32
  _: i32
  Stat3Value: Tags
  _: i32
  Stat4Value: Tags
  _: GrantedEffectsPerLevel
  SpawnWeight_Tags: [ModAuraFlags]
  SpawnWeight_Values: [i32]
  Tags: [AchievementItems]
  GrantedEffectsPerLevel: [ModType]
  AuraFlags: [i32]
  MonsterMetadata: Stats
  MonsterKillAchievements: [AchievementItems]
  ChestModType: [AchievementItems]
  Stat5Value: Tags
  _: i32
  Stat5: AchievementItems
  FullAreaClear_AchievementItems: [AchievementItems]
  AchievementItems: [Stats]
  GenerationWeight_Tags: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [ItemClasses]
  Stat6Value: i32
  _: i32
  Stat6: AchievementItems
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [Stats]
  MonsterOnDeath: Stats
  _: i32
  HeistAchievements: [AchievementItems]
  Heist_SubStatValue1: InfluenceTypes
  Heist_SubStatValue2: Tags
  Heist_Stat0: Stats
  Heist_Stat1: Stats
  Heist_AddStatValue1: i32
  Heist_AddStatValue2: i32
  InfluenceType: i32
  ImplicitTags: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: BuffTemplates
  _: Mods
  _: i32
  _: i32
  _: i32
  _: GrantedEffectsPerLevel
  BuffTemplate: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: u32 @unique
  _: [rid]
  _: i32
  _: [GrantedEffectsPerLevel]
  RadiusJewelType: i32
  IsEssenceOnlyModifier: bool
  _: i32
}
