# Added 4.1
type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModType: ModType
  Level: i32
  Stat1: Stats
  Stat2: Stats
  Stat3: Stats
  Stat4: Stats
  Domain: ModDomains
  Name: string @localized
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Value: i32
  _: i32
  Stat2Value: i32
  _: i32
  Stat3Value: Tags
  _: i32
  Stat4Value: Tags
  _: GrantedEffectsPerLevel
  SpawnWeight_Tags: [ModAuraFlags]
  _: [i32]
  Tags: [Tags]
  GrantedEffectsPerLevel: [GrantedEffectsPerLevel]
  AuraFlags: [i32]
  _: [_]
  _: string
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
  _: rid
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
  _: rid
  _: i32
  _: bool
  _: [_] # All rows empty
  _: string
  _: i32
  _: [_] # All rows empty
  _: i32
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
  _: i32
  _: [_]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32 @unique
  _: [_]
  _: bool
  _: u16 # All rows empty
  _: bool
  _: [_] # All rows empty
  _: i32
  _: bool
  _: i32
  _: [_]
}
