# Added 4.1
type MonsterDeathConditions {
  Id: string @unique
  BuffDefinition: [BuffDefinitions]
  _: bool
  _: i32
  Stat: [Stats]
  _: bool
  _: i32
  Rarity: Rarity
  _: bool
  Mods: [Mods]
  _: i32
  _: bool
  _: [_]
  _: i32
  _: rid
  _: rid
  _: i32
  _: bool
  _: u16 # All rows empty
  _: bool
}
