# Added 4.1
type MonsterShapeShift {
  Id: i32 @unique
  MonsterSource: MonsterVarieties
  MonsterShapeshift: MonsterVarieties
  EffectSource: MiscEffectPacks
  EffectDestination: MiscEffectPacks
  _: [string]
  _: [string]
  _: [string]
  _: [string]
  BuffTemplate: BuffTemplates
  _: rid
  _: string
  _: string
}
