# Added 4.1
type MonsterDeathAchievements {
  Id: string @unique
  MonsterVarietiesKeys: [MonsterVarieties]
  AchievementItemsKeys: [AchievementItems]
  _: bool
  PlayerConditionsKeys: [PlayerConditions]
  MonsterDeathConditionsKeys: [MonsterDeathConditions]
  _: [rid]
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: rid
  _: i32 # All rows empty
  _: [_] # All rows empty
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: bool
  _: i32 @unique
  _: i32 # All rows empty
  _: bool
  _: i32 # All rows empty
}
