# Added 4.1
type MonsterConditions {
  Id: string @unique
  Rarity: Rarity
  Stat: Stats
  NotRarity: Rarity
  NotStat: [Stats]
  MapBoss: bool
  NotMapBoss: bool
  Tags: [Tags]
  NotTags: [Tags]
  _: i32
  MinimumLevel: i32
  MaximumLevel: i32
  HASH32: u32
  BuffDefinition: BuffDefinitions
}
