# Added 4.1
type MonsterPacks {
  Id: string @unique
  WorldAreas: [WorldAreas]
  MinCount: i32
  MaxCount: i32
  BossMonsterSpawnChance: i32
  BossCount: i32
  BossMonsters: [MonsterVarieties]
  _: bool
  _: [i32]
  Grounds: [string]
  Tags: [Tags]
  MinLevel: i32
  MaxLevel: i32
  WorldAreas2: [Tags]
  PackFormation: PackFormation
  _: i32
  _: bool
  _: [string]
  _: bool
  _: bool
  _: string
  _: bool
  _: bool
  AdditionalMonsters: [MonsterVarieties]
  AdditionalCounts: [i32]
  _: bool
  _: rid
}
