# Added 4.1
type MoveDaemon {
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: rid
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32
  _: bool
  _: MoveDaemon
  _: i32
  _: bool
  _: bool
  _: i32 # All rows empty
  _: bool
  _: i32
  _: i32
  _: bool
}
