# Added 4.1
type MtxTypeGameSpecific {
  Type: MtxTypes @unique
  HASH32: u32
  DDSFile: string @file(ext: ".dds")
  _: i32
  _: [_]
  _: bool
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
}
