# Added 4.1
type NPCFollowerVariations {
  MonsterVarietiesKey: MonsterVarieties
  MiscAnimatedKey0: MiscAnimated
  MiscAnimatedKey1: MiscAnimated
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_] # All rows empty
  QuestFlag: [QuestFlags]
  _: i32
  _: bool
  _: bool
  _: i32
  _: string
  _: rid
  _: i32
}
