# Added 4.1
type NPCShop {
  Id: string @unique
  _: i32
  TabColours: [Colours]
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
  _: i32
  NPCs: [NPCs]
  _: i32
  _: i32
  _: [_] # All rows empty
  _: i32
  _: bool
  _: rid
}
