# Added 4.1
type NPCs {
  Id: string @unique
  Name: string @localized
  Metadata: string @files(ext: [".ot", ".otc"])
  QuestFlags: QuestFlags
  NPCMasterKey: NPCMaster
  ShortName: string @localized
  Act: i32
  NPCAudios1: [NPCAudio]
  NPCAudios2: [NPCAudio]
  HASH16: u16
  _: NPCs
  Portrait: NPCPortraits
  DialogueStyle: NPCDialogueStyles
  ShopSet: NPCShopSets
  Gender: string
  _: bool
  _: string
  NPCType: NPCType
}
