# Added 4.3
type NPCTalkDialogueTextAudio {
  Id: string @unique
  TargetCharacter: Characters
  Text: string @localized
  OGGFiles: [string] @file(ext: ".ogg")
  NPC1: [NPCs]
  _: rid
  TargetCharacters: [Characters]
  _: i32
  _: i32
  _: [_] # All rows empty
  NPC2: [NPCs]
  NPC3: [NPCs]
  QuestFlag1: [QuestFlags]
  QuestFlag2: [QuestFlags]
  QuestFlag3: [QuestFlags]
  QuestFlag4: [QuestFlags]
  QuestFlag5: [QuestFlags]
  Video: NPCTalkVideo
  Script: string
}
