# Added 4.1
type NPCTalk {
  NPCKey: NPCs
  _: i32
  DialogueOption: string @localized
  _: [QuestFlags]
  _: [QuestFlags]
  _: [QuestFlags]
  Script: string
  TextAudio: NPCTextAudio
  Category: NPCTalkCategory
  QuestRewardOffersKey: QuestRewardOffers
  QuestFlag: QuestFlags
  NPCTextAudioKeys: [NPCTextAudio]
  Script2: string
  _: bool
  _: bool
  _: [i32]
  _: [i32]
  _: i32
  _: [i32]
  _: i32
  _: bool
  BaseItemTypes: BaseItemTypes
  _: [i32]
  _: bool
  DialogueOption2: string
  ConsoleQuickAction: NPCTalkConsoleQuickActions
  Music1: Music
  _: i32
  _: [_] # All rows empty
  _: i32
  Music2: Music
  _: i32
  QuestFlag2: QuestFlags
  _: bool
  _: i32
  _: NPCTalk
  TalkDialogue: [NPCTalkDialogue]
}
