# Added 4.1
type PassiveSkillTrees {
  Id: string @unique
  _: i32
  _: f32
  _: f32
  _: f32
  _: i32 @unique
  _: i32 @unique
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
  _: bool
}
