# Added 4.3
type passivejewelradiiart {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: [_]
  _: i32
  _: i32
  _: string
  _: i32
  _: i32 # All rows empty
  _: bool
}
