# Added 4.1
type PassiveSkillTreeUIArt {
  Id: string @unique
  GroupBackgroundSmall: string
  GroupBackgroundMedium: string
  GroupBackgroundLarge: string
  _: bool
  PassiveFrameNormal: string
  NotableFrameNormal: string
  KeystoneFrameNormal: string
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: string
  _: rid
}
