# Added 4.1
type Pet {
  Id: string @unique
  MtxTypeGameSpecific: MtxTypeGameSpecific @unique
  HASH16: u16
  HASH32: u32
  Size: i32
  _: bool
  _: bool
  HideoutTags: [HideoutDoodadTags]
  HideoutCategory: HideoutDoodadCategory
  GrantedSkill: [GrantedEffectsPerLevel]
  _: i32
  _: bool
  _: rid
  _: bool
  _: bool
  _: bool
  _: string
  ReviveEffect: MicrotransactionReviveEffects
}
