# Added 4.1
type PlayerConditions {
  Id: string @unique
  BuffDefinitionsKeys: [BuffDefinitions]
  _: bool
  BuffStacks: i32
  CharactersKey: Characters
  StatsKeys: [Stats]
  _: bool
  StatValue: i32
  _: [rid]
  _: bool
}
