# Added 4.1
type PreloadFromStats {
  Stat: Stats @unique
  Animation: [MiscAnimated]
  Object: [MiscObjects]
  BuffVisual: [BuffVisuals]
  EffectPack: [MiscEffectPacks]
  _: i32
  GroundEffectType: [GroundEffectTypes]
}
