# Added 4.1
type Projectiles {
  Id: string @unique @files(ext: [".ot", ".otc"])
  AOFiles: [string] @file(ext: ".ao")
  LoopAnimationIds: [string]
  ImpactAnimationIds: [string]
  "Raw speed. The client multiplies this by 0.092 to get world units per second"
  ProjectileSpeed: i32
  "Projectile ends at point where user clicks on the screen"
  UseTargetLocation: bool
  CollisionRadius: i32
  RandomizeVisualRotationOnSpawn: bool
  _: bool
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  MiscAnimated: MiscAnimated
  "Wider radius used to find collision candidates"
  CollisionCandidateRadius: i32
  ApplyProjectileSpeedToAuxiliarySpeed: bool
  AuxiliarySpeedCannotBeBelowBase: bool
  Stuck_AOFile: [string] @file(ext: ".ao")
  Bounce_AOFile: string @file(ext: ".ao")
  _: i32
  _: i32
  _: i32
  _: i32
  MiscAnimatedFlash: MiscAnimated
  MiscAnimatedArrowNova: MiscAnimated
  _: i32
  _: i32
  VisualScaleMinPercent: i32
  VisualScaleMaxPercent: i32
  MiscEffectPackArtVariation: i32
  FizzleAnimationNames: [string]
  InheritOwnerVisualScale: bool
  CollisionBehaviourFlags: [i32]
  _: string
  MiscAnimatedBounce: MiscAnimated
  MiscAnimatedImpact: MiscAnimated
  DamageEffect1: DamageEffectVariations
  _: bool
  _: string
  DamageEffect2: DamageEffectVariations
  _: string
  BounceOverride: BallisticBounceOverride
  _: string
  _: [string]
  _: [string]
  _: bool
}
