# Added 4.1
type QuestItems {
  BaseItemType: BaseItemTypes @unique
  TriggeredQuestFlag: QuestFlags
  QuestComplete: QuestFlags
  _: i32
  _: [_] # All rows empty
  _: bool
  _: bool
  HelpText: ClientStrings
  Description: ClientStrings
  Script: string
  _: rid
  QuestFlag: QuestFlags
  _: i32
  NPCs: [NPCs]
  QuestFlagUsed: QuestFlags
  BuffVisual: BuffVisuals
}
