# Added 4.1
type RogueExiles {
  MonsterVarietiesKey: MonsterVarieties @unique
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: [i32]
  AudioCharacter: AudioCharacterClass
  _: rid
  _: rid
  _: rid
  _: rid
  Name: Words
}
