# Added 4.1
type SentinelPassives {
  Id: string @unique
  HASH16: i32
  _: string @localized
  Stats: [SentinelPassiveStats]
  _: [i32]
  _: i32
  _: i32
  PassiveType: SentinelPassiveTypes
  _: i32
  _: i32
  _: i32
}
