# Added 4.1
type SingleGroundLaser {
  Id: i32 @unique
  MiscBeams: MiscBeams
  MiscAnimated: MiscAnimated
  _: i32
  _: string
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  MiscBeamsPulse: MiscBeams
  MiscAnimatedPulse: MiscAnimated
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
}
