# Added 4.1
type SkillSurgeEffects {
  Id: string @unique
  GrantedEffectsKey: GrantedEffects
  Stat: Stats
  SurgeType: SurgeTypes
  _: string
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: [rid]
  _: f32
  _: rid
  _: rid
}
