# Added 4.1
type SkillArtVariations {
  Id: string @unique
  AnimatedArt: [MiscAnimatedArtVariations]
  BeamArt: [MiscBeamsArtVariations]
  EffectPacksArt: [MiscEffectPacksArtVariations]
  ObjectArt: [MiscObjectsArtVariations]
  Variants: [string]
  BuffVisuals: [BuffVisualsArtVariations]
  _: [i32]
  ProjectileArt: [ProjectilesArtVariations]
  Stat: Stats
  MonsterVarieties: [MonsterVarietiesArtVariations]
  ActiveSkill: [ActiveSkills]
  GrantedEffect: [GrantedEffects]
  _: [string]
  _: i32
  _: [_]
  _: [_]
  _: [_]
  _: rid
}
