# Added 4.1
type SkillMorphDisplay {
  Skill: ActiveSkills
  BuffDefinitions: [BuffDefinitions]
  DDSFiles: [string] @file(ext: ".dds")
  _: i32
  Overlay: [string]
  _: i32
  _: [f32]
  _: bool
  _: bool
  ActiveSkill: ActiveSkills
  _: bool
}
