# Added 4.1
type SoulCores {
  BaseItemType: BaseItemTypes @unique
  RequiredLevel: i32
  Limit: SoulCoreLimits
  Description: ClientStrings2
  Type: SoulCoreTypes
  TierHigher: SoulCores
  IsSocketBound: bool
  _: bool
  _: bool
  _: bool
  ExtraDescription: ClientStrings2
  _: bool
  _: bool
}
