# Added 4.1
type StatisticTrackingMicrotransactionsStatistics {
  StatisticTrackingMtx: StatisticTrackingMicrotransactions
  _: i32
  _: i32
  VisualIdentity: ItemVisualIdentity
  _: bool
  Icon: string
  _: bool
  Description: ClientStrings2
  CounterType: StatisticTrackingMicrotransactionCounterType
  _: i32
  _: i32
  _: bool
  _: bool
}
