# Added 4.2
type tempesttypes {
  _: string @unique
  _: rid @unique
  _: rid
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: i32 @unique
  _: u16 # All rows empty
}
