# Added 4.1
type TieredMicrotransactions {
  MTX: MtxTypeGameSpecific @unique
  TierThresholds: [i32]
  _: Stats
  _: [i32]
  _: Stats
  TierCount: i32
  _: [Stats]
  _: [i32]
  _: [i32]
  _: bool
  _: bool
  _: Stats
  _: bool
  _: [_]
}
