# Added 4.1
type TriggerBeam {
  _: i32
  _: [MiscBeams]
  _: [MiscBeams]
  _: [i32]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: [i32]
  _: bool
  _: i32
  _: bool
  _: [string]
  _: [_] # All rows empty
  _: bool
}
