# Added 4.1
type visualpinproperties {
  _: string @unique
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
  _: i32
  _: i32
  _: bool
  _: bool
  _: f32
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: bool
}
