# Added 4.1
type Words {
  Wordlist: Wordlists
  Text: string
  SpawnWeight_Tags: [Tags]
  SpawnWeight_Values: [i32]
  HASH32: i32
  Text2: string @localized
  "the inflection identifier used for i18n in related fields"
  Inflection: string @localized
}
