# Added 3.11
type AlternateSkillTargetingBehaviours {
  Id: string @unique
  "Maximum targeting distance used when no actor-specific override applies"
  MaxDistance: i32
  ClientStrings: ClientStrings
  MaxMineTargetingDistance: i32
  MaxTrapTargetingDistance: i32
  MaxTotemTargetingDistance: i32
  TargetingFlags: [i32]
}
