# Added 3.22
type AncestralTrialMonsters {
  Unit: AncestralTrialUnits
  Monster: MonsterVarieties
  Animation: MiscAnimated
  _: i32
  Achievement: [AchievementItems]
  _: bool
  _: bool
  _: bool
  _: bool
}
