# Added 3.22
type AncestralTrialFieldItems {
  Unit: AncestralTrialUnits
  Object: MiscObjects
  HASH32: u32
  Description: string @localized
  Achievement: [AchievementItems]
  SoundEffectPurchase: SoundEffects
  SoundEffectPlace: SoundEffects
}
