# Added 3.22
type AncestralTrialTribes {
  Id: string @unique
  NPC: NPCs
  Portrait: string
  TribeIcon: string
  TribeName: string @unique @localized
  FavourTracker: string
  _: [rid]
  Name: string @localized
  _: rid
  _: rid
  _: rid
  _: rid
  _: [rid]
  _: rid
  _: [rid]
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
}
