# Added 3.22
type AncestralTrialDialogue {
  Tribe: AncestralTrialTribes
  TrialEvent: AncestralTrialDialogueEvents
  _: i32
  TextAudio: [NPCTextAudio]
  Character: Characters
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
}
