# Added 3.22
type AncestralTrialTribes {
  Id: string @unique
  NPCHub: NPCs
  Portrait: string
  TribeIcon: string
  TribeName: string @localized
  FavourTracker: string
  UnlockQuestFlag: [QuestFlags]
  Name: string @localized
  QuestFlagLike: QuestFlags
  QuestFlagDislike: QuestFlags
  QuestFlagFightLost: QuestFlags
  QuestFlagFightWin: QuestFlags
  Achievement: [AchievementItems]
  MinimapIcon: MinimapIcons
  AchievementRuthless: [AchievementItems]
  _: i32
  _: i32
  _: i32
  _: i32
  NPCArena: NPCs
}
