# Added 3.17
type ArchnemesisModVisuals {
  Id: string @unique
  MiscAnimated: MiscAnimated
  StampFamily: StampFamily
  MiscEffectPack: MiscEffectPacks
  BuffVisual: [BuffVisuals]
  Monster: [MonsterVarieties]
  MonsterMiscAnimated: [MiscAnimated]
  MonsterEffectPack: [MiscEffectPacks]
}
