# Added 3.11
type AreaTransitionInfo {
  StartingArea: WorldAreas
  EndingArea: WorldAreas
  AnimationType: AreaTransitionAnimationTypes
  AnimationMarauder: AreaTransitionAnimations
  AnimationRanger: AreaTransitionAnimations
  AnimationWitch: AreaTransitionAnimations
  AnimationDualist: AreaTransitionAnimations
  AnimationTemplar: AreaTransitionAnimations
  AnimationShadow: AreaTransitionAnimations
  AnimationScion: AreaTransitionAnimations
  Animation: MiscAnimated
  MiscObjectGround: [MiscObjects]
  _: i32
  BossObject: [MiscObjects]
}
