# Added 3.11
type AreaTransitionInfo {
  StartingArea: WorldAreas
  EndingArea: WorldAreas
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  _: rid
  Animation: MiscAnimated
  MiscObject: [MiscObjects]
  _: i32
  _: [rid]
}
