# Added 3.11
type Ascendancy {
  Id: string @unique
  ClassNo: i32
  _: [_]
  _: string @unique
  _: string
  _: string @unique @localized
  _: string @unique @localized
  _: string @unique
  _: string @unique
  _: i32
  _: i32
  _: string @unique
  _: string @unique @localized
  _: string @unique @localized
  _: string
  _: string
  _: [_] # All rows empty
}
