# Added 3.11
type AtlasNode {
  Id: string @unique
  Area1: WorldAreas
  _: bool
  FlavourText: FlavourText
  Connections: [AtlasNode]
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  UniqueArt: string @file(ext: ".dds")
  StartingNode: bool
  NotOnAtlas: bool
  DivCards: [BaseItemTypes]
  DivCardsHardmode: [BaseItemTypes]
  _: i32
  HASH16: i16
  _: bool
  _: i32
  _: i32
  _: [_] # All rows empty
  _: bool
  _: bool
  WatchstoneSlot: rid
  _: rid
  QuestStates: [i32]
  _: bool
  _: rid
  Area2: WorldAreas
  _: bool
  _: bool
  _: f32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
}
