# Added 3.17
type AtlasInfluenceData {
  InfluencePack: AtlasInfluenceOutcomes
  MonsterPacks: [MonsterPacks]
  BuffDefinition: BuffDefinitions
  _: [Stats]
  BuffStatValues: [i32]
  _: [MonsterPackCounts]
  _: i32
  _: i32
  InfluencePackSizeStat: Stats
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  ZanaInfluenceChanceStat: Stats
  ZanaInfluenceMagicChanceStat: Stats
  ZanaInfluenceRareChanceStat: Stats
}
