# Added 3.17
type AtlasPrimordialBosses {
  Id: string @unique
  _: i32
  _: i32
  _: i32
  _: i32
  InfluenceComplete: MiscAnimated
  MiniBossInvitation: BaseItemTypes
  BossInvitation: BaseItemTypes
  PickUpKey: QuestFlags
  MinorBossKey: QuestItems
  BossQuestKey: QuestItems
  Tag: Tags
  Altar: MiscObjects
  AltarActivated: MiscAnimated
  OppositeTag: Tags
}
