# Added 3.11
type AtlasNode {
  Id: string @unique
  Area1: WorldAreas
  _: bool
  FlavourText: FlavourText
  Connections: [AtlasNode]
  _: f32
  _: f32
  _: f32
  _: f32
  _: f32
  UniqueArt: string @file(ext: ".dds")
  StartingNode: bool
  NotOnAtlas: bool
  DivCards: [BaseItemTypes]
  DivCardsHardmode: [BaseItemTypes]
  Tier: i32
  HASH16: i16
  IsUniqueMap: bool
  Region: AtlasRegions
  Node_DDSFile: string @file(ext: ".dds")
  IsNormalMap: bool
  RequiresSpecificItem: bool
  VoidstoneSlot: AtlasVoidstoneSlots
  MapDeviceLayout: MapDeviceLayouts
  QuestStates: [i32]
  _: bool
  _: rid
  Area2: WorldAreas
  _: bool
  _: bool
  _: f32
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
}
