# Added 3.11
type AtlasNodeDefinition {
  Id: string @unique
  Area1: WorldAreas
  _: i32
  _: i32
  NotOnAtlas: bool
  IsUniqueMap: bool
  Node_DDSFile: string @file(ext: ".dds")
  IsNormalMap: bool
  RequiresSpecificItem: bool
  VoidstoneSlot: AtlasVoidstoneSlots
  MapDeviceLayout: MapDeviceLayouts
  QuestStates: [i32]
  _: bool
  NodeDisplayName: ClientStrings2
  Area2: WorldAreas
  _: bool
  Header: MapNodeHeader
  _: i32
}
