# Added 3.11
type AwardDisplay {
  Id: string @unique
  Text: string @localized
  BackgroundImage: string
  _: i32
  _: f32
  _: f32
  _: string
  _: string
  ForegroundImage: string
  OGGFile: string @file(ext: ".ogg")
  QuestFlag: QuestFlags
  _: i32
  _: string @localized
  _: bool
}
