# Added 3.23
type AzmeriWoodsDustType {
  Id: string @unique
  BaseItemType: BaseItemTypes
  _: string @localized
  _: string
  ChargeAnimation: MiscAnimated
  ReleaseAnimation: MiscAnimated
  Stats: Stats
  BeamArt: MiscBeams
  WeatherArt: MiscAnimated
  Text: string @localized
}
