# Added 3.11
type BaseItemTypes @tags(list: ["item:def", "item:droptable"]) {
  Id: string @unique
  ItemClassesKey: ItemClasses
  Width: i32
  Height: i32
  Name: string @localized
  InheritsFrom: string @files(ext: [".ot", ".otc"])
  DropLevel: i32
  FlavourTextKey: FlavourText
  Implicit_ModsKeys: [Mods]
  SizeOnGround: i32
  SoundEffect: SoundEffects
  TagsKeys: [Tags]
  ModDomain: ModDomains
  ItemVisualIdentity: ItemVisualIdentity
  HASH32: i32
  _: i32 @unique
  _: [_]
  _: string @localized
  _: rid
  _: bool
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: i32
  _: i32
  _: bool
  _: rid
  _: rid
  _: bool
  _: rid
  _: bool
  _: [_]
  _: [_]
  _: bool
  _: bool
  _: rid
}
