# Added 3.17
type BattlePassRewards {
  BattlePass: BattlePasses
  RewardTier: i32
  _: i32
  _: i32
  _: bool
  Id: string
  RewardedMTX: [MtxTypeGameSpecific]
  _: i32
  RewardDescription: string @localized
  _: string
  _: i32
  _: i32
  _: bool
  RewardTitle: string @localized
  ItemFrameType: ItemFrameType
  _: i32
  _: i32
  _: i32
  _: i32
  BaseItemTypeReward: BaseItemTypes
  _: i32
}
