# Added 3.11
type BetrayalJobs {
  Id: string @unique
  Text: string @localized
  ExtraTerrainFeaturesKey: ExtraTerrainFeatures
  Art: string
  _: i32
  _: i32
  WorldAreasKey: WorldAreas
  Completion_AchievementItemsKey: [AchievementItems]
  OpenChests_AchievementItemsKey: [AchievementItems]
  MissionCompletion_AcheivementItemsKey: [AchievementItems]
  _: string @unique
}
