# Added 3.11
type BetrayalDialogue {
  Id: BetrayalTargets
  _: i32
  _: i32
  _: [i32]
  BetrayalTargetsKey: BetrayalTargets
  _: i32
  Job: BetrayalJobs
  Relationship: [BetrayalRelationshipState]
  BetrayalUpgradesKey: BetrayalUpgrades
  _: bool
  _: [i32]
  PossibleChoices: [BetrayalChoiceActions]
  _: bool
  _: [i32]
  NPCTextAudioKey: NPCTextAudio
  _: [i32]
}
