# Added 3.27
type brequelfruitrewardtypes {
  _: string @unique
  _: string @unique @localized
  _: string @unique @localized
  _: string @unique @localized
  _: string @unique @localized
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: rid @unique
  _: rid @unique
}
