# Added 3.11
type BuffDefinitions {
  Id: string @unique
  Description: string @localized
  Invisible: bool
  Removable: bool
  Name: string @localized
  StatsKeys: [Stats]
  CancelOnDeath: bool
  _: i32
  ShowCount: bool
  Maximum_StatsKey: Stats
  Current_StatsKey: Stats
  _: bool
  _: i32
  BuffVisualsKey: BuffVisuals
  _: bool
  _: bool
  BuffCategory: i32
  _: bool
  _: bool
  _: bool
  _: bool
  BuffLimit: i32
  _: bool
  Id2: string
  IsRecovery: bool
  _: bool
  MinStat: Stats
  _: bool
  UIStackMode: i32
  _: bool
  IsSkillBuff: bool
  _: i32
  _: [i32]
  _: bool
  _: bool
  MultiPartAchievement: [MultiPartAchievements]
  _: bool
  Stats2: [Stats]
  GrantedFlags: [Stats]
  GrantedStats: [Stats]
  ConditionStats: [Stats]
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: Stats
  _: [i32]
  _: string @localized
  _: [Stats]
  _: bool
}
