# Added 3.11
type ClientStrings {
  Id: string @unique
  Text: string @localized
  XBoxText: string @localized
  XBoxText2: string @localized
  HASH32: u32
  PlaystationText: string @localized
  _: string @localized
}
