# Added 3.20
type CoreLeagues {
  Id: string @unique
  _: bool
  _: bool
  DisableChanceStat: Stats
  DisableStat: [Stats]
  LeagueChanceStat: Stats
  AdditionalLeagueChanceStat: Stats
  BaseLeagueChanceStat: Stats
  ForcedSpawnStat: [Stats]
  LeagueCountOverrideStat: Stats
  _: rid
  _: i32
  _: bool
  _: Stats
  _: bool
  _: bool
  _: [Stats]
  _: bool
  _: Stats
}
