# Added 3.21
type CurrencyUseEffects {
  CurrencyItem: BaseItemTypes @unique
  _: i32
  BK2File: string @file(ext: ".bk2")
  _: bool
  BK2File2: string @file(ext: ".bk2")
  _: bool
  Stat: Stats
  _: f32
  SoundEffect: SoundEffects
}
