# Added 3.29
type DeepwaterCraftingCurrencies {
  Currency: CurrencyItems
  _: i32
  _: i32
  _: i32
  Cost: i32
  _: i32
  _: [_] # All rows empty
  _: [_] # All rows empty
  NPCAudio: NPCTextAudio
  _: i32
  _: string @localized
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
}
