type DeepwaterCraftingCurrencies {
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: [_] # All rows empty
  _: [_] # All rows empty
  _: rid
  _: i32
  _: string @localized
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
}
