type DeepwaterRooms {
  Id: string @unique
  _: string
  _: i32
  _: string @localized
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32
  _: rid
  _: i32
  _: i32
  _: [rid]
  _: [i32]
  _: DeepwaterRooms
  _: bool
  _: [rid]
  _: bool
}
