# Added 3.29
type DeepwaterRooms {
  Id: string @unique
  ArmFiles: string @file(ext: ".arm")
  _: i32
  Name: string @localized
  _: i32
  _: i32
  _: i32
  Biome: DeepwaterBiomes
  _: i32
  _: rid
  _: i32
  _: i32
  Stats: [Stats]
  StatValues: [i32]
  _: DeepwaterRooms
  Special: bool
  AchievementItems: [AchievementItems]
  _: bool
}
