# Added 3.23
type Descendancy {
  Id: string @unique
  Name: string @localized
  BackgroundImage: string
  FlavourText: string @localized
  CoordinateRect: string
  RGBFlavourTextColour: string
  UnlockCondition: string @localized
  _: rid
  _: rid
  _: i32
  UIArt: PassiveSkillTreeUIArtAscendancy
  _: rid
}
