# Added 3.11
type GeometryTrigger {
  Id: i32 @unique
  GrantedEffect: GrantedEffects
  Animation: MiscAnimated
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: f32
  _: i32
  _: i32
  GroundMarker: [MiscAnimated]
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: i32
  _: i32
  Stats: [Stats]
  StatValues: [i32]
  _: i32
  _: f32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
}
