# Added 3.11
type GeometryAttack {
  Id: i32 @unique
  Animation: [MiscAnimated] @unique
  HitEffect: [MiscAnimated]
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: [_] # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  BuffDefinition: BuffDefinitions
  BuffValues: [i32]
  _: i32
  _: bool
  _: bool
  BuffVisual: BuffVisuals
  _: bool
  _: [i32]
  _: bool
  _: bool
  GeometryChannel: GeometryChannel
  _: bool
  _: bool
  _: [_] # All rows empty
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  ExecuteGeal: ExecuteGEAL
  GroundEffect: GroundEffectTypes
  MonsterVariety: [MonsterVarieties]
}
