# Added 3.11
type GeometryProjectiles {
  Id: i32 @unique
  Projectile: Projectiles
  _: bool
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  GeometryChannel: GeometryChannel
  _: bool
  _: rid
  _: i32
}
