# Added 3.18
type GrantedEffectStatSets {
  Id: string @unique
  ImplicitStats: [Stats]
  ConstantStats: [Stats]
  ConstantStatsValues: [i32]
  BaseEffectiveness: f32
  _: f32
  IncrementalEffectiveness: f32
}
