type graphicalitemexchangeslot {
  _: rid
  _: rid @unique
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: bool
  _: i32
  _: i32 @unique
  _: bool
  _: i32
  _: i32
  _: i32
  _: [_]
  _: string
  _: bool
  _: i32
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: bool
}
