# Added 3.29
type graphicalitemreceptacle {
  _: [_]
  _: rid
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: rid
  _: i32 # All rows empty
  _: i32
  _: rid
  _: i32 # All rows empty
  _: i32
  _: bool
  _: rid
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: i32
  _: i32
  _: i32 # All rows empty
  _: i32
  _: i32 # All rows empty
  _: rid
  _: rid
  _: u16 # All rows empty
  _: bool
}
