# Added 3.11
type GroundEffects {
  GroundEffectTypesKey: GroundEffectTypes
  _: i32
  _: i32
  BuffVisual1: BuffVisuals
  _: f32
  _: [i32]
  _: bool
  AOFile: [string] @file(ext: ".ao")
  _: [string]
  EndEffect: string
  BuffVisual2: BuffDefinitions
  MiscObject1: MiscObjects
  MiscObject2: MiscObjects
  _: rid
  _: rid
  _: bool
  _: bool
  _: bool
  BuffVisual3: BuffVisuals
  _: rid
  _: bool
  _: bool
  _: bool
}
