# Added 3.20
type HardModeExtraContentChances {
  Id: string @unique
  SingleSpawnChance: i32
  DoubleSpawnChance: i32
  TripleSpawnChance: i32
  NoSpawnChance: i32
  Leagues: [CoreLeagues]
  _: bool
}
