# Added 3.12
type HeistDoodadNPCs {
  NPCsKey: NPCs
  QuestFlag1: QuestFlags
  QuestFlag2: QuestFlags
  _: i32
  _: i32
  _: i32
  AOFile: string @file(ext: ".ao")
  Stance: string
  BetrayalTargetsKey: BetrayalTargets
}
