# Added 3.21
type HudVisualsFromStat {
  Stat: Stats @unique
  LifeVisual: HudLifeVisuals
  EnergyShieldVisual: HudEnergyShieldVisuals
  ManaVisual: HudManaVisuals
  TradeVisual: TradeWindowVisuals
  ManaFlaskVisual: HudManaVisuals
  _: bool
}
