# Added 3.11
type IncursionRooms @tags(list: ["item:itemized"]) {
  Id: string @unique
  Name: string @localized
  Tier: i32
  MinLevel: i32
  RoomUpgrade_IncursionRoomsKey: IncursionRooms
  Mods: [Mods]
  PresentARMFile: string @file(ext: ".arm")
  HASH16: u32
  IncursionArchitectKey: IncursionArchitect
  PastARMFile: string @file(ext: ".arm")
  TSIFile: string @file(ext: ".tsi")
  UIIcon: string
  FlavourText: string @localized
  Description: string @localized
  AchievementItemsKeys: [AchievementItems]
  _: i32
  _: i32
  RoomUpgradeFrom_IncursionRoomsKey: IncursionRooms
  ItemisedFlavourText: FlavourText
  _: string @localized
  _: [Mods]
}
