# Added 3.11
type IncursionChestRewards @tags(list: ["item:droptable"]) {
  IncursionRoomsKey: IncursionRooms
  IncursionChestsKeys: [IncursionChests]
  ChestMarkerMetadata: string @files(ext: [".ot", ".otc"])
  HASH32: u32
  RuthlessIncursionChestsKeys: [IncursionChests]
  _: i32
  _: i32
  _: i32
  _: i32
}
