# Added 3.26
type itemvisualheldmodeloverridebyitemaffiliatedattributes {
  _: rid @unique
  _: string
  _: [_] # All rows empty
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
}
