# Added 3.11
type ItemClasses @tags(list: ["crafting"]) {
  Id: string @unique
  Name: string @localized
  ItemClassCategory: ItemClassCategories
  _: rid
  _: bool
  _: [_] # All rows empty
  _: [_]
  _: bool
  _: bool
  _: bool
  _: rid
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
  _: [_]
  _: [_]
  _: bool
  _: bool
  _: rid
  _: bool
  _: bool
  _: bool
  _: bool
}
