# Added 3.11
type LabyrinthSecretEffects {
  Id: string @unique
  MonsterVarietiesKey: MonsterVarieties
  Buff_BuffDefinitionsKey: BuffDefinitions
  Buff_StatValues: [i32]
  OTFile: string @file(ext: ".ot")
  Buff_StatValuesRuthless: [i32]
}
