# Added 3.23
type LabyrinthCraftOptions {
  Id: string @unique
  CraftFamily: LabyrinthCraftOptionFamily
  Text: string @localized
  Script: string
  ScriptArgument: string
  HASH16: u16
  _: bool
  Tier: LabyrinthCraftOptionTiers
  _: bool
  Achievement: [AchievementItems]
  _: bool
  SoundEffect: SoundEffects
  _: i32
}
