# Added 3.11
type MapConnections {
  MapPinsKey0: MapPins
  MapPinsKey1: MapPins
  QuestCompleteFlag: QuestFlags
  RestrictedAreaText: string @localized
  QuestGainedFlag: QuestFlags
  _: QuestFlags
  _: QuestFlags
  _: [_] # All rows empty
}
