# Added 3.11
type MapCompletionAchievements {
  _: string
  MapStatConditionsKeys: [MapStatConditions]
  StatsKeys: [Stats]
  AchievementItemsKeys: [AchievementItems]
  MapTierAchievementsKeys: [MapTierAchievements]
  _: bool
  WorldAreasKeys: [WorldAreas]
  Ruleset: [Rulesets]
}
