# Added 3.11
type MapPins {
  Id: string @unique
  "X starts at left side of image, can be negative"
  PositionX: i32
  "Y starts at top side of image, can be negative"
  PositionY: i32
  Waypoint_WorldAreasKey: WorldAreas
  WorldAreasKeys: [WorldAreas]
  Name: string @localized
  FlavourText: string @localized
  QuestFlags: [QuestFlags]
  Act: i32
  _: string
  QuestFlagVisit: [QuestFlags]
  QuestFlagKill: QuestFlags
  _: rid
}
