# Added 3.19
type MemoryLineType {
  Id: string @unique
  MemoryLine: AtlasMemoryLine
  HASH16: u16
  Stats: [Stats]
  StatValues: [i32]
  _: i32
  Suffix: string @localized
  _: i32
  _: i32
  FinalAtlasNode: AtlasNode
  _: i32
  Tier: i32
  CurrencyItem: BaseItemTypes
}
