# Added 3.19
type MemoryLineType {
  Id: string @unique
  MemoryLine: AtlasMemoryLine
  HASH16: i16
  _: [_]
  _: [i32]
  _: i32 @unique
  _: string @localized
  _: i32
  _: rid
  _: i32 # All rows empty
  _: i32
  _: i32
  _: rid
}
