# Added 3.26
type MercenarySupports {
  Id: string @unique
  _: i32
  _: i32
  _: i32
  Stat: [Stats]
  StatValues: [i32]
  Name: string @localized
  SupportFamily: MercenarySupportFamilies
  HASH16: u16
  GemIcon: string
  Variant: i32
  _: [_] # All rows empty
  _: [_] # All rows empty
}
