# Added 3.26
type MercenaryBuilds {
  Id: string @unique
  Class: MercenaryClasses
  Skill1: [MercenarySkills]
  _: i32
  Skill2: [MercenarySkills]
  _: i32
  _: [_] # All rows empty
  _: i32
  Skill3: [MercenarySkills]
  _: [string]
  Tags: [Tags]
  AIFile: string
  HASH16: u16
  BuildName: string @localized
  _: i32
  Infamous: bool
  IdleSkill: MercenarySkills
  _: string
  _: [string]
  Achievements: [AchievementItems]
  WieldableTypes: [MercenaryWieldableTypes]
  _: [_]
}
