# Added 3.26
type MercenaryBuilds {
  Id: string @unique
  Class: MercenaryClasses
  Skills1: [MercenarySkills]
  Skills2Count: i32
  Skills2: [MercenarySkills]
  _: i32
  _: [_] # All rows empty
  Skills3Count: i32
  Skills3: [MercenarySkills]
  _: [string]
  Tags: [Tags]
  AIFile: string
  HASH16: u16
  Name: string @localized
  _: i32
  IsInfamous: bool
  IdleSkill: MercenarySkills
  _: string
  _: [string]
  Achievements: [AchievementItems]
  WieldableTypes: [MercenaryWieldableTypes]
  ExtraStats: [MercenaryBuildExtraStats]
}
