# Added 3.26
type MercenarySkills {
  GrantedEffect: GrantedEffects
  SupportCount: MercenarySupportCounts
  PossibleSupports: [MercenarySupports]
  EncounterGrantedEffect: GrantedEffects
  Name: string @localized
  Description: string @localized
  RequiredLevel: i32
  _: i32
  SkillFamily: MercenarySkillFamilies
  HASH16: u16
  HouseIcon: string
}
