# Added 3.17
type MicrotransactionJewelVariations {
  Mtx: MtxTypeGameSpecific @unique
  _: i32
  ActiveArt: string
  BackgroundArt: string
  _: i32
  BackgroundPupil: string
  JewelCircle1: string
  JewelCircle2: string
  JewelCircleGlow: string
  _: i32
  _: i32
  SmokeRing: string
  _: i32
  Ring: string
  _: i32
  _: i32
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
}
