# Added 3.19
type MicrotransactionConditionalApparitions {
  Id: string @unique
  Stats: [Stats]
  StatValues: [i32]
  PeriodicVariation: MicrotransactionPeriodicCharacterEffectVariations
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
}
