# Added 3.23
type MicrotransactionLevelUpEffects {
  Id: string @unique
  Animation: MiscAnimated
  EffectPack: MiscEffectPacks
  Stat: Stats
  MiscObject: MiscObjects
  _: string
  Script: string
  _: string
  SoundEffect: LevelUpSoundEffect
}
