# Added 3.11
type MicrotransactionPortalVariations {
  MtxTypeGameSpecific: MtxTypeGameSpecific @unique
  Index: i16
  AOFile: string @file(ext: ".ao")
  MapAOFile: string @file(ext: ".ao")
  _: f32
  MiscObject: MiscObjects
  PortalEffect: string @file(ext: ".ao")
  _: f32
  OTFile: string @file(ext: ".ot")
  PortalEffectLarge: string @file(ext: ".ao")
  _: i32
  _: i32
  Script: string
}
