# Added 3.21
type MicrotransactionOnKillEffects {
  Id: string @unique
  ObjectEffect1: MicrotransactionObjectEffects
  ObjectEffect2: MicrotransactionObjectEffects
  KillCondition: MicrotransactionOnKillConditions
  HASH32: u32
  OnKillBeam: MicrotransactionOnKillBeams
  _: i32
  Stat: Stats
  Counter: [MicrotransactionCounters]
  _: [i32]
}
