# Added 3.11
type MissionTimerTypes {
  Id: string @unique
  Image: string
  BackgroundImage: string
  SoundEffects: [SoundEffects]
  _: [f32]
  _: SoundEffects
  _: SoundEffects
  _: string
  _: string
  _: f32
  _: i32
}
