# Added 3.12
type ModEffectStats {
  StatsKey: Stats
  TagsKeys: [Tags]
  ApplyToExplicit: bool
  _: i32
  ApplyToImplicit: bool
  ApplyToPrefix: bool
  ApplyToSuffix: bool
  Multiplier: i32
  ApplyToEnchant: bool
}
