# Added 3.11
type Mods @tags(list: ["crafting"]) {
  Id: string @unique
  HASH16: u16
  ModTypeKey: ModType
  Level: i32
  StatsKey1: Stats
  StatsKey2: Stats
  StatsKey3: Stats
  StatsKey4: Stats
  Domain: ModDomains
  Name: string @localized
  GenerationType: ModGenerationType
  Families: [ModFamily]
  Stat1Min: i32
  Stat1Max: i32
  Stat2Min: i32
  Stat2Max: i32
  Stat3Min: i32
  Stat3Max: i32
  Stat4Min: i32
  Stat4Max: i32
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  TagsKeys: [Tags]
  GrantedEffectsPerLevelKeys: [GrantedEffectsPerLevel]
  _: [rid]
  MonsterMetadata: string
  MonsterKillAchievements: [AchievementItems]
  ArchnemesisType: [ModType]
  Stat5Min: i32
  Stat5Max: i32
  StatsKey5: Stats
  FullAreaClear_AchievementItemsKey: [AchievementItems]
  AchievementItemsKey: [AchievementItems]
  GenerationWeight_TagsKeys: [Tags]
  GenerationWeight_Values: [i32]
  ModifyMapsAchievements: [AchievementItems]
  IsEssenceOnlyModifier: bool
  Stat6Min: i32
  Stat6Max: i32
  StatsKey6: Stats
  MaxLevel: i32
  _: bool
  CraftingItemClassRestrictions: [ItemClasses]
  MonsterOnDeath: string
  _: i32
  HeistAchievements: [AchievementItems]
  Stat7Min: i32
  Stat7Max: i32
  StatsKey7: Stats
  StatsKey8: Stats
  Stat8Min: i32
  Stat8Max: i32
  InfluenceTypes: InfluenceTypes
  ImplicitTagsKeys: [Tags]
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  BuffTemplate1: BuffTemplates
  ArchnemesisMinionMod: Mods
  HASH32: u32
  BuffTemplate2: [BuffTemplates]
  GameMode: GameModes
  GrantedEffectRuthless: [GrantedEffectsPerLevel]
  _: bool
}
