# Added 3.11
type MonsterDeathAchievements {
  Id: string @unique
  MonsterVarietiesKeys: [MonsterVarieties]
  AchievementItemsKeys: [AchievementItems]
  _: bool
  PlayerConditionsKeys: [PlayerConditions]
  MonsterDeathConditionsKeys: [MonsterDeathConditions]
  _: [rid]
  _: i32
  _: i32
  _: bool
  _: bool
  Stats: [Stats]
  MultiPartAchievement1: [MultiPartAchievements]
  MapAchievement: [MapTierAchievements]
  MultiPartAchievement2: [MultiPartAchievements]
  MultiPartAchievement3: MultiPartAchievements
  _: i32
  NearbyMonsterConditionsKeys: [NearbyMonsterConditions]
  _: bool
  MultiPartAchievementConditionsKeys: [MultiPartAchievementConditions]
  _: [i32]
  _: bool
  Area: [WorldAreas]
  Stat: [Stats]
  _: bool
}
