# Added 3.11
type MonsterDeathConditions {
  Id: string @unique
  BuffDefinition: [BuffDefinitions]
  _: bool
  _: i32
  Stat: [Stats]
  _: bool
  _: i32
  Rarity: Rarity
  _: bool
  Mods: [Mods]
  _: i32
  _: [_]
  _: i32
  _: rid
  _: rid
  _: i32
  _: i32
}
