# Added 3.11
type MonsterDeathConditions {
  Id: string @unique
  BuffDefinition: [BuffDefinitions]
  _: bool
  _: i32
  Stat: [Stats]
  _: bool
  _: i32
  Rarity: Rarity
  _: bool
  Mods: [Mods]
  _: i32
  _: bool
  Animation: [Animation]
  _: i32
  ActiveSkill1: ActiveSkills
  ActiveSkill2: ActiveSkills
  _: i32
  _: i32
}
