# Added 3.11
type MonsterMortar {
  Id: i32 @unique
  Projectile: Projectiles
  Animation: Animation
  ImpactAnimation: MiscAnimated
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32
  _: bool
  _: bool
  BounceAnimation: MiscAnimated
  _: i32
  _: f32
  _: f32
  _: f32
  _: bool
  ImpactAnimation2: MiscAnimated
  _: string
}
