# Added 3.11
type NPCMaster {
  Id: string @unique
  Signature_ModsKey: Mods
  SpawnWeight_TagsKeys: [Tags]
  SpawnWeight_Values: [i32]
  _: rid
  Achievement: [AchievementItems]
  AfflictionAchievement: [AchievementItems]
  League: CoreLeagues
}
