# Added 3.11
type NPCs {
  Id: string @unique
  Name: string @localized
  Metadata: string @files(ext: [".ot", ".otc"])
  QuestFlags: QuestFlags
  NPCMasterKey: NPCMaster
  ShortName: string @localized
  _: i32
  NPCAudios1: [NPCAudio]
  NPCAudios2: [NPCAudio]
  HASH16: u16
  _: NPCs
  Portrait: NPCPortraits
  DialogueStyle: NPCDialogueStyles
  _: bool
  ShopSet: NPCShopSets
  Gender: string
  _: bool
  _: i32
}
