# Added 3.11
type NPCTalk {
  NPCKey: NPCs
  _: i32
  DialogueOption: string @localized
  QuestFlag1: [QuestFlags]
  QuestFlag2: [QuestFlags]
  QuestFlag3: [QuestFlags]
  Script: string
  QuestFlag4: QuestFlags
  Category: NPCTalkCategory
  QuestRewardOffersKey: QuestRewardOffers
  QuestFlag5: QuestFlags
  NPCTextAudioKeys: [NPCTextAudio]
  Script2: string
  _: bool
  _: bool
  _: [i32]
  _: [i32]
  _: i32
  _: [i32]
  _: i32
  _: bool
  BaseItemTypes: BaseItemTypes
  _: i32
  _: bool
  DialogueOption2: string @localized
  ConsoleQuickAction: NPCTalkConsoleQuickActions
  Music1: Music
  _: i32
  _: [_] # All rows empty
  _: i32
  Music2: Music
  _: i32
  _: rid
  _: bool
  _: i32
  _: NPCTalk
  Inventory: Inventories
}
