# Added 3.17
type PassiveSkillTreeUIArt {
  Id: string @unique
  _: bool
  Ornament: string
  BackgroundArt: PassiveSkillTreeGroupBackgroundArt
  PassiveFrame: PassiveSkillTreeNodeFrameArt
  NotableFrame: PassiveSkillTreeNodeFrameArt
  KeystoneFrame: PassiveSkillTreeNodeFrameArt
}
