# Added 3.14
type PassiveSkillTrees {
  Id: string @unique
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: rid
  _: rid
  _: i32 # All rows empty
  _: bool
  _: string @unique
}
