type passiveskilltreeuiartascendancy {
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string @unique
  _: string
  _: string @unique
  _: string @unique
  _: string @unique
  _: string
  _: [_]
  _: [_]
}
