# Added 3.11
type PassiveSkillTreeTutorial {
  Id: string @unique
  CharactersKey: Characters
  PassiveChoiceA: PassiveSkills
  ChoiceA_Description: string @localized
  ChoiceB_Description: string @localized
  PassiveChoiceB: PassiveSkills
  ChoiceA_PassiveTreeURL: string
  ChoiceB_PassiveTreeURL: string
  NotableChoiceA: PassiveSkills
  NotableChoiceB: PassiveSkills
}
