# Added 3.20
type SanctumRoomTypes {
  Id: string @unique
  _: bool
  _: bool
  _: rid
  _: rid
  _: bool
  Icon: string
  _: bool
  Description: string @localized
  _: [string] @localized
  Rooms: [SanctumRooms]
  _: string
  _: bool
}
