# Added 3.18
type SentinelPassives {
  Id: string @unique
  HASH16: i32
  _: string
  Stats: [SentinelPassiveStats]
  _: [i32]
  _: i32
  _: i32
  PassiveType: SentinelPassiveTypes
  _: i32
  _: i32
  _: i32
}
