# Added 3.14
type SkillArtVariations {
  Id: string @unique
  _: [rid]
  _: [i32]
  _: [i32]
  _: [i32]
  Variants: [string]
  _: [rid]
  _: [i32]
  _: [rid]
  _: rid
  _: [i32]
  _: [rid]
  _: [i32]
}
