# Added 3.11
type SkillSurgeEffects {
  Id: string @unique
  GrantedEffectsKey: GrantedEffects
  Stat: Stats
  _: string
  _: bool
  _: bool
  _: bool
  MiscAnimated: MiscAnimated
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: bool
  _: [_] # All rows empty
  _: i32
}
