# Added 3.11
type SpawnObject {
  Id: i32 @unique
  MiscObjects: [MiscObjects] @unique
  _: [_] # All rows empty
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: string
  _: i32
  _: bool
  _: i32
}
