# Added 3.23
type StatisticTrackingMicrotransactionsStatistics {
  Id: StatisticTrackingMicrotransactions
  _: i32
  _: i32
  ItemVisualIdentity: ItemVisualIdentity
  _: bool
  Icon: string
  _: bool
  Text: ClientStrings
  Type: StatisticTrackingMicrotransactionCounterType
}
