# Added 3.11
type Stats @tags(list: ["crafting"]) {
  Id: string @unique
  _: bool
  IsLocal: bool
  IsWeaponLocal: bool
  Semantics: StatSemantics
  _: string @localized
  _: bool
  _: bool
  _: i32
  _: i32
  _: i32
  _: i32
  _: bool
  _: i32 @unique
  _: [string]
  _: rid
  _: bool
  _: bool
  _: bool
  _: [_]
  _: [_]
}
