# Added 3.11
type SummonedSpecificMonsters {
  Id: i32 @unique
  MonsterVarietiesKey: MonsterVarieties
  "Fallback key used to load game-object resources when MonsterVarietiesKey is null"
  GameObjectRegisterKey: i32
  SummonEffect: MiscAnimated
  _: bool
  _: bool
  _: i32
  _: i32
  _: bool
  BuffDefinition: BuffDefinitions
  BuffVisual: BuffVisuals
  _: i32
  _: bool
  _: i32
  _: string
  _: bool
  _: bool
  _: i32
}
