# Added 3.11
type SynthesisFragmentDialogue {
  Area: SynthesisAreas
  NPCTextAudioKey1: NPCTextAudio
  NPCTextAudioKey2: NPCTextAudio
  NPCTextAudioKey3: NPCTextAudio
  NPCTextAudioKey4: NPCTextAudio
  NPCTextAudioKey5: NPCTextAudio
  NPCTextAudioKey6: NPCTextAudio
}
