# Added 3.11
type UniqueMaps @tags(list: ["item:unique"]) {
  ItemVisualIdentityKey: ItemVisualIdentity @unique
  WorldAreasKey: WorldAreas
  WordsKey: Words
  FlavourTextKey: FlavourText
  _: bool
  Name: string @localized
  IsDropDisabled: bool
}
