# Added 3.25
type villageshippingports {
  _: string @unique
  _: string @unique @localized
  _: string
  _: string @unique
  _: string @unique @localized
  _: bool
  _: i32 @unique
  _: i32 @unique
  _: i32 @unique
  _: i32
  _: i32 @unique
  _: bool
  _: f32
  _: rid
}
