# Added 3.11
type WorldAreas {
  Id: string @unique
  Name: string @localized
  Act: i32
  IsTown: bool
  HasWaypoint: bool
  Connections_WorldAreasKeys: [WorldAreas]
  AreaLevel: i32
  HASH16: i16
  _: i32
  _: i32
  LoadingScreens: [string] @file(ext: ".dds")
  _: rid
  _: [_]
  _: i32
  _: [_]
  _: i32
  _: i32
  _: i32
  _: rid
  _: rid
  _: [_]
  _: [_]
  _: [_]
  _: [_]
  _: bool
  _: [_]
  _: rid
  _: rid
  _: [_]
  _: i32
  _: [_]
  _: bool
  _: i32
  _: [_]
  _: bool
  _: string @localized
  _: i32
  _: i32
  _: [_]
  _: bool
  _: bool
  _: bool
  _: rid
  _: rid
  _: string
  _: rid
  _: [_] # All rows empty
  _: bool
  _: bool
  _: rid
  _: rid
  _: string
  _: i32
  _: rid
  _: i32
  _: rid
  _: bool
  _: bool
  _: i32
  _: i32 # All rows empty
  _: i32 # All rows empty
  _: [_]
  _: rid
  _: rid
  _: rid
  _: i32 # All rows empty
  _: rid
  _: i32
  _: rid
}
