name: export data

on:
  workflow_dispatch:
  push:
    branches: [ "develop" ]
  schedule:
    - cron: 20 */4 * * *

env:
  NODE_OPTIONS: "--max_old_space_size=16000"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: npm install
        run: npm ci
      - name: get version
        id: get-version
        run: echo "version=$(curl --fail 'https://ggpk.exposed/version?poe=1' | sed -r 's|.*/([0-9](\.[0-9]+)+)/$|\1|') / $(curl --fail 'https://ggpk.exposed/version?poe=2' | sed -r 's|.*/([0-9](\.[0-9]+)+)/$|\1|')" >> "$GITHUB_OUTPUT"
      - name: cache cdn downloads
        uses: actions/cache@v3
        with:
          path: .cache
          key: poecdn-${{ steps.get-version.outputs.version }}

      - run: npx -y tsx src/validate.ts --quiet
      - run: npx -y tsx src/validate.ts --poe2 --quiet
      - run: find * -name *.csv -size +50M -print -delete

      - name: commit changes
        id: autocommit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "export data at version ${{ steps.get-version.outputs.version }}"
      - name: upload gh-pages artifact
        if: github.event_name == 'workflow_dispatch' || steps.autocommit.outputs.changes_detected == 'true'
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: current

    outputs:
      changes_detected: ${{ steps.autocommit.outputs.changes_detected }}

  deploy:
    runs-on: ubuntu-latest

    needs: build
    if: github.event_name == 'workflow_dispatch' || needs.build.outputs.changes_detected == 'true'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy gh-pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
